name: settings_ui
description: Create native settings for Flutter app in minutes. Use single interfaces to build
version: 1.0.0-nullsafety.2
homepage: https://github.com/yako-dev/flutter-settings-ui

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
